# Default values for dolibarr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # Global Docker image registry
  imageRegistry: ""

  # Global Docker registry secret names as an array
  imagePullSecrets: []

# Override Kubernetes version
kubeVersion: ""

nameOverride: ""
fullnameOverride: ""

# Annotations to add to all deployed objects
commonAnnotations: {}

# Labels to add to all deployed objects
commonLabels: {}

# Array of extra objects to deploy with the release
extraDeploy: []

# Number of replicas (do not change it)
replicaCount: 1

updateStrategy:
  # Update strategy type (do not change it)
  type: Recreate

image:
  # Image registry
  registry: docker.io

  # Image repository
  repository: tuxgasy/dolibarr

  # Image tag
  tag: 17.0.2

  # Image digest
  digest: ""

  # Image pull policy
  pullPolicy: IfNotPresent

pdb:
  # Specifies whether a pod disruption budget should be created
  create: false

  # Minimum number/percentage of pods that should remain scheduled
  minAvailable: 1

  # Maximum number/percentage of pods that may be made unavailable
  # maxUnavailable: 1

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

# Additional pod annotations
podAnnotations: {}

# Additional pod labels
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

# Priority class name
# priorityClassName : high-priority

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

livenessProbe:
  # Enable liveness probe
  enabled: true

  # Delay before the liveness probe is initiated
  initialDelaySeconds: 180

  # How often to perform the liveness probe
  periodSeconds: 10

  # When the liveness probe times out
  timeoutSeconds: 1

  # Minimum consecutive failures for the liveness probe to be considered failed after having succeeded
  failureThreshold: 3

  # Minimum consecutive successes for the liveness probe to be considered successful after having failed
  successThreshold: 1

readinessProbe:
  # Enable readiness probe
  enabled: true

  # Delay before the readiness probe is initiated
  initialDelaySeconds: 0

  # How often to perform the readiness probe
  periodSeconds: 10

  # When the readiness probe times out
  timeoutSeconds: 1

  # Minimum consecutive failures for the readiness probe to be considered failed after having succeeded
  failureThreshold: 3

  # Minimum consecutive successes for the readiness probe to be considered successful after having failed
  successThreshold: 1

service:
  # Service annotations
  annotations: {}

  # Service type
  type: ClusterIP

  # Static cluster IP address or None for headless service when service type is ClusterIP
  # clusterIP: 10.43.0.100

  # Static load balancer IP address when service type is LoadBalancer
  # loadBalancerIP: 10.0.0.100

  # Source IP address ranges when service type is LoadBalancer
  # loadBalancerSourceRanges:
  #   - 10.0.0.0/24

  # External traffic routing policy when service type is LoadBalancer or NodePort
  externalTrafficPolicy: Cluster

  # Service port
  port: 80

  # Service node port when service type is LoadBalancer or NodePort
  # nodePort: 30000

ingress:
  enabled: false

  # IngressClass that will be be used to implement the Ingress
  ingressClassName: ""

  # Ingress path type
  pathType: ImplementationSpecific

  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: dolibarr.local
      paths:
        - /
  tls: []
  #  - secretName: dolibarr-tls
  #    hosts:
  #      - dolibarr.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

extraArgs: {}
  # name: ""

# Additional container environment variables
extraEnvVars: []
#  - name: MY-NAME
#    value: "MY-VALUE"

# Name of existing ConfigMap containing additional container environment variables
extraEnvVarsCM:

# Name of existing Secret containing additional container environment variables
extraEnvVarsSecret:

init:
  # Init security context
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  # Init CPU/Memory resource requests/limits
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

persistence:
  # Enable persistence using PVC
  enabled: false

  # Name of an existing PVC to use
  # existingClaim: my-pvc

  # PVC access mode
  accessMode: ReadWriteOnce

  # PVC annotations
  annotations: {}

  # PVC size
  size: 1Gi

  # PVC storage class
  # storageClass: -

dolibarr:
  admin:
    # Administrator username
    username: admin

    # Administrator password
    password: admin

  # External URL
  externalUrl: http://dolibarr.local

  cron:
    # Enable cron for scheduled jobs
    enabled: false

    # Cron username
    username: admin

    # Cron security key
    securityKey: ""

# Name of existing Secret to use
existingSecret: ""

mariadb:
  # Whether to use the MariaDB chart
  enabled: true

  # MariaDB architecture
  architecture: standalone

  auth:
    # MariaDB database
    database: dolibarr

    # MariaDB user
    username: dolibarr

    # MariaDB password
    password: dolibarr

    # Name of existing Secret to use
    existingSecret: ""

  primary:
    service:
      ports:
        # MariaDB port
        mysql: 3306

externalMariadb:
  # Whether to use an external MariaDB
  enabled: false

  # External MariaDB host
  host: mariadb

  # External MariaDB port
  port: 3306

  # External MariaDB user
  username: dolibarr

  # External MariaDB password
  password: dolibarr

  # Name of existing Secret to use
  existingSecret: ""

  # Name of the key in existing Secret that contains MariaDB password
  existingSecretKeyPassword: mariadb-password

  # External MariaDB database
  database: dolibarr

tests:
  image:
    # Image registry
    registry: ghcr.io

    # Image repository
    repository: cowboysysop/pytest

    # Image tag
    tag: 1.0.35

    # Image digest
    digest: ""

    # Image pull policy
    pullPolicy: IfNotPresent
